version: '3.8'
services:
  go-protoc:
    image: golang:1.24.1-alpine
    container_name: go-protoc
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "8080:8080"
    environment:
      - PATH=$PATH:/usr/local/bin
    command: >
      sh -c "
        apk add --no-cache curl unzip protobuf &&
        go install google.golang.org/protobuf/cmd/protoc-gen-go@latest &&
        go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest &&
        /bin/sh
      "
    tty: true
    stdin_open: true