// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.0
// 	protoc        v5.29.1
// source: internal/pb/curso_categoria.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Blank struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Blank) Reset() {
	*x = Blank{}
	mi := &file_internal_pb_curso_categoria_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Blank) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Blank) ProtoMessage() {}

func (x *Blank) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_curso_categoria_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Blank.ProtoReflect.Descriptor instead.
func (*Blank) Descriptor() ([]byte, []int) {
	return file_internal_pb_curso_categoria_proto_rawDescGZIP(), []int{0}
}

type Categoria struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Nome          string                 `protobuf:"bytes,2,opt,name=nome,proto3" json:"nome,omitempty"`
	Descricao     string                 `protobuf:"bytes,3,opt,name=descricao,proto3" json:"descricao,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Categoria) Reset() {
	*x = Categoria{}
	mi := &file_internal_pb_curso_categoria_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Categoria) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Categoria) ProtoMessage() {}

func (x *Categoria) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_curso_categoria_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Categoria.ProtoReflect.Descriptor instead.
func (*Categoria) Descriptor() ([]byte, []int) {
	return file_internal_pb_curso_categoria_proto_rawDescGZIP(), []int{1}
}

func (x *Categoria) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Categoria) GetNome() string {
	if x != nil {
		return x.Nome
	}
	return ""
}

func (x *Categoria) GetDescricao() string {
	if x != nil {
		return x.Descricao
	}
	return ""
}

type CreateCategoria struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nome          string                 `protobuf:"bytes,1,opt,name=nome,proto3" json:"nome,omitempty"`
	Descricao     string                 `protobuf:"bytes,2,opt,name=descricao,proto3" json:"descricao,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCategoria) Reset() {
	*x = CreateCategoria{}
	mi := &file_internal_pb_curso_categoria_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCategoria) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCategoria) ProtoMessage() {}

func (x *CreateCategoria) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_curso_categoria_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCategoria.ProtoReflect.Descriptor instead.
func (*CreateCategoria) Descriptor() ([]byte, []int) {
	return file_internal_pb_curso_categoria_proto_rawDescGZIP(), []int{2}
}

func (x *CreateCategoria) GetNome() string {
	if x != nil {
		return x.Nome
	}
	return ""
}

func (x *CreateCategoria) GetDescricao() string {
	if x != nil {
		return x.Descricao
	}
	return ""
}

type ListaDeCategorias struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Categoria     []*Categoria           `protobuf:"bytes,1,rep,name=categoria,proto3" json:"categoria,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListaDeCategorias) Reset() {
	*x = ListaDeCategorias{}
	mi := &file_internal_pb_curso_categoria_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListaDeCategorias) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListaDeCategorias) ProtoMessage() {}

func (x *ListaDeCategorias) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_curso_categoria_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListaDeCategorias.ProtoReflect.Descriptor instead.
func (*ListaDeCategorias) Descriptor() ([]byte, []int) {
	return file_internal_pb_curso_categoria_proto_rawDescGZIP(), []int{3}
}

func (x *ListaDeCategorias) GetCategoria() []*Categoria {
	if x != nil {
		return x.Categoria
	}
	return nil
}

type GetCategoriaByIdInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCategoriaByIdInput) Reset() {
	*x = GetCategoriaByIdInput{}
	mi := &file_internal_pb_curso_categoria_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCategoriaByIdInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCategoriaByIdInput) ProtoMessage() {}

func (x *GetCategoriaByIdInput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_curso_categoria_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCategoriaByIdInput.ProtoReflect.Descriptor instead.
func (*GetCategoriaByIdInput) Descriptor() ([]byte, []int) {
	return file_internal_pb_curso_categoria_proto_rawDescGZIP(), []int{4}
}

func (x *GetCategoriaByIdInput) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_internal_pb_curso_categoria_proto protoreflect.FileDescriptor

var file_internal_pb_curso_categoria_proto_rawDesc = []byte{
	0x0a, 0x21, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x62, 0x2f, 0x63, 0x75,
	0x72, 0x73, 0x6f, 0x5f, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x61, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x07, 0x0a, 0x05, 0x42, 0x6c, 0x61, 0x6e, 0x6b,
	0x22, 0x4d, 0x0a, 0x09, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x61, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x6f, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x6f, 0x6d,
	0x65, 0x12, 0x1c, 0x0a, 0x09, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x63, 0x61, 0x6f, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x63, 0x61, 0x6f, 0x22,
	0x43, 0x0a, 0x0f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72,
	0x69, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x6f, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x6f, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x63, 0x61, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x64, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x63, 0x61, 0x6f, 0x22, 0x40, 0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74, 0x61, 0x44, 0x65, 0x43,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x61, 0x73, 0x12, 0x2b, 0x0a, 0x09, 0x63, 0x61, 0x74,
	0x65, 0x67, 0x6f, 0x72, 0x69, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70,
	0x62, 0x2e, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x61, 0x52, 0x09, 0x63, 0x61, 0x74,
	0x65, 0x67, 0x6f, 0x72, 0x69, 0x61, 0x22, 0x27, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x43, 0x61, 0x74,
	0x65, 0x67, 0x6f, 0x72, 0x69, 0x61, 0x42, 0x79, 0x49, 0x64, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x32,
	0xcd, 0x02, 0x0a, 0x10, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x61, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x36, 0x0a, 0x0e, 0x43, 0x72, 0x69, 0x61, 0x72, 0x43, 0x61, 0x74,
	0x65, 0x67, 0x6f, 0x72, 0x69, 0x61, 0x12, 0x13, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x61, 0x1a, 0x0d, 0x2e, 0x70, 0x62,
	0x2e, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x61, 0x22, 0x00, 0x12, 0x46, 0x0a, 0x14,
	0x43, 0x72, 0x69, 0x61, 0x72, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x61, 0x53, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x12, 0x13, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x61, 0x1a, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x4c,
	0x69, 0x73, 0x74, 0x61, 0x44, 0x65, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x61, 0x73,
	0x22, 0x00, 0x28, 0x01, 0x12, 0x42, 0x0a, 0x16, 0x43, 0x72, 0x69, 0x61, 0x72, 0x43, 0x61, 0x74,
	0x65, 0x67, 0x6f, 0x72, 0x69, 0x61, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x42, 0x49, 0x12, 0x13,
	0x2e, 0x70, 0x62, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f,
	0x72, 0x69, 0x61, 0x1a, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72,
	0x69, 0x61, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x12, 0x35, 0x0a, 0x0f, 0x4c, 0x69, 0x73, 0x74,
	0x61, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x61, 0x73, 0x12, 0x09, 0x2e, 0x70, 0x62,
	0x2e, 0x42, 0x6c, 0x61, 0x6e, 0x6b, 0x1a, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x4c, 0x69, 0x73, 0x74,
	0x61, 0x44, 0x65, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x61, 0x73, 0x22, 0x00, 0x12,
	0x3e, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x61, 0x42,
	0x79, 0x49, 0x64, 0x12, 0x19, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x61, 0x74, 0x65,
	0x67, 0x6f, 0x72, 0x69, 0x61, 0x42, 0x79, 0x49, 0x64, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x1a, 0x0d,
	0x2e, 0x70, 0x62, 0x2e, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x61, 0x22, 0x00, 0x42,
	0x0d, 0x5a, 0x0b, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_pb_curso_categoria_proto_rawDescOnce sync.Once
	file_internal_pb_curso_categoria_proto_rawDescData = file_internal_pb_curso_categoria_proto_rawDesc
)

func file_internal_pb_curso_categoria_proto_rawDescGZIP() []byte {
	file_internal_pb_curso_categoria_proto_rawDescOnce.Do(func() {
		file_internal_pb_curso_categoria_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_pb_curso_categoria_proto_rawDescData)
	})
	return file_internal_pb_curso_categoria_proto_rawDescData
}

var file_internal_pb_curso_categoria_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_internal_pb_curso_categoria_proto_goTypes = []any{
	(*Blank)(nil),                 // 0: pb.Blank
	(*Categoria)(nil),             // 1: pb.Categoria
	(*CreateCategoria)(nil),       // 2: pb.CreateCategoria
	(*ListaDeCategorias)(nil),     // 3: pb.ListaDeCategorias
	(*GetCategoriaByIdInput)(nil), // 4: pb.GetCategoriaByIdInput
}
var file_internal_pb_curso_categoria_proto_depIdxs = []int32{
	1, // 0: pb.ListaDeCategorias.categoria:type_name -> pb.Categoria
	2, // 1: pb.CategoriaService.CriarCategoria:input_type -> pb.CreateCategoria
	2, // 2: pb.CategoriaService.CriarCategoriaStream:input_type -> pb.CreateCategoria
	2, // 3: pb.CategoriaService.CriarCategoriaStreamBI:input_type -> pb.CreateCategoria
	0, // 4: pb.CategoriaService.ListaCategorias:input_type -> pb.Blank
	4, // 5: pb.CategoriaService.GetCategoriaById:input_type -> pb.GetCategoriaByIdInput
	1, // 6: pb.CategoriaService.CriarCategoria:output_type -> pb.Categoria
	3, // 7: pb.CategoriaService.CriarCategoriaStream:output_type -> pb.ListaDeCategorias
	1, // 8: pb.CategoriaService.CriarCategoriaStreamBI:output_type -> pb.Categoria
	3, // 9: pb.CategoriaService.ListaCategorias:output_type -> pb.ListaDeCategorias
	1, // 10: pb.CategoriaService.GetCategoriaById:output_type -> pb.Categoria
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_pb_curso_categoria_proto_init() }
func file_internal_pb_curso_categoria_proto_init() {
	if File_internal_pb_curso_categoria_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_pb_curso_categoria_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_pb_curso_categoria_proto_goTypes,
		DependencyIndexes: file_internal_pb_curso_categoria_proto_depIdxs,
		MessageInfos:      file_internal_pb_curso_categoria_proto_msgTypes,
	}.Build()
	File_internal_pb_curso_categoria_proto = out.File
	file_internal_pb_curso_categoria_proto_rawDesc = nil
	file_internal_pb_curso_categoria_proto_goTypes = nil
	file_internal_pb_curso_categoria_proto_depIdxs = nil
}
