// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.24.4
// source: proto/curso_categoria.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CategoriaService_CriarCategoria_FullMethodName = "/pb.CategoriaService/CriarCategoria"
)

// CategoriaServiceClient is the client API for CategoriaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CategoriaServiceClient interface {
	CriarCategoria(ctx context.Context, in *CreateCategoria, opts ...grpc.CallOption) (*CategoriaResponse, error)
}

type categoriaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCategoriaServiceClient(cc grpc.ClientConnInterface) CategoriaServiceClient {
	return &categoriaServiceClient{cc}
}

func (c *categoriaServiceClient) CriarCategoria(ctx context.Context, in *CreateCategoria, opts ...grpc.CallOption) (*CategoriaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CategoriaResponse)
	err := c.cc.Invoke(ctx, CategoriaService_CriarCategoria_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CategoriaServiceServer is the server API for CategoriaService service.
// All implementations must embed UnimplementedCategoriaServiceServer
// for forward compatibility.
type CategoriaServiceServer interface {
	CriarCategoria(context.Context, *CreateCategoria) (*CategoriaResponse, error)
	mustEmbedUnimplementedCategoriaServiceServer()
}

// UnimplementedCategoriaServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCategoriaServiceServer struct{}

func (UnimplementedCategoriaServiceServer) CriarCategoria(context.Context, *CreateCategoria) (*CategoriaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CriarCategoria not implemented")
}
func (UnimplementedCategoriaServiceServer) mustEmbedUnimplementedCategoriaServiceServer() {}
func (UnimplementedCategoriaServiceServer) testEmbeddedByValue()                          {}

// UnsafeCategoriaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CategoriaServiceServer will
// result in compilation errors.
type UnsafeCategoriaServiceServer interface {
	mustEmbedUnimplementedCategoriaServiceServer()
}

func RegisterCategoriaServiceServer(s grpc.ServiceRegistrar, srv CategoriaServiceServer) {
	// If the following call pancis, it indicates UnimplementedCategoriaServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CategoriaService_ServiceDesc, srv)
}

func _CategoriaService_CriarCategoria_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCategoria)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategoriaServiceServer).CriarCategoria(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CategoriaService_CriarCategoria_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategoriaServiceServer).CriarCategoria(ctx, req.(*CreateCategoria))
	}
	return interceptor(ctx, in, info, handler)
}

// CategoriaService_ServiceDesc is the grpc.ServiceDesc for CategoriaService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CategoriaService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.CategoriaService",
	HandlerType: (*CategoriaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CriarCategoria",
			Handler:    _CategoriaService_CriarCategoria_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/curso_categoria.proto",
}
