// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: internal/pb/curso_categoria.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Blank struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Blank) Reset() {
	*x = Blank{}
	mi := &file_internal_pb_curso_categoria_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Blank) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Blank) ProtoMessage() {}

func (x *Blank) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_curso_categoria_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Blank.ProtoReflect.Descriptor instead.
func (*Blank) Descriptor() ([]byte, []int) {
	return file_internal_pb_curso_categoria_proto_rawDescGZIP(), []int{0}
}

type Categoria struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Nome          string                 `protobuf:"bytes,2,opt,name=nome,proto3" json:"nome,omitempty"`
	Descricao     string                 `protobuf:"bytes,3,opt,name=descricao,proto3" json:"descricao,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Categoria) Reset() {
	*x = Categoria{}
	mi := &file_internal_pb_curso_categoria_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Categoria) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Categoria) ProtoMessage() {}

func (x *Categoria) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_curso_categoria_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Categoria.ProtoReflect.Descriptor instead.
func (*Categoria) Descriptor() ([]byte, []int) {
	return file_internal_pb_curso_categoria_proto_rawDescGZIP(), []int{1}
}

func (x *Categoria) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Categoria) GetNome() string {
	if x != nil {
		return x.Nome
	}
	return ""
}

func (x *Categoria) GetDescricao() string {
	if x != nil {
		return x.Descricao
	}
	return ""
}

type CreateCategoria struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nome          string                 `protobuf:"bytes,1,opt,name=nome,proto3" json:"nome,omitempty"`
	Descricao     string                 `protobuf:"bytes,2,opt,name=descricao,proto3" json:"descricao,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCategoria) Reset() {
	*x = CreateCategoria{}
	mi := &file_internal_pb_curso_categoria_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCategoria) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCategoria) ProtoMessage() {}

func (x *CreateCategoria) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_curso_categoria_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCategoria.ProtoReflect.Descriptor instead.
func (*CreateCategoria) Descriptor() ([]byte, []int) {
	return file_internal_pb_curso_categoria_proto_rawDescGZIP(), []int{2}
}

func (x *CreateCategoria) GetNome() string {
	if x != nil {
		return x.Nome
	}
	return ""
}

func (x *CreateCategoria) GetDescricao() string {
	if x != nil {
		return x.Descricao
	}
	return ""
}

type ListaDeCategorias struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Categoria     []*Categoria           `protobuf:"bytes,1,rep,name=categoria,proto3" json:"categoria,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListaDeCategorias) Reset() {
	*x = ListaDeCategorias{}
	mi := &file_internal_pb_curso_categoria_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListaDeCategorias) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListaDeCategorias) ProtoMessage() {}

func (x *ListaDeCategorias) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_curso_categoria_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListaDeCategorias.ProtoReflect.Descriptor instead.
func (*ListaDeCategorias) Descriptor() ([]byte, []int) {
	return file_internal_pb_curso_categoria_proto_rawDescGZIP(), []int{3}
}

func (x *ListaDeCategorias) GetCategoria() []*Categoria {
	if x != nil {
		return x.Categoria
	}
	return nil
}

var File_internal_pb_curso_categoria_proto protoreflect.FileDescriptor

const file_internal_pb_curso_categoria_proto_rawDesc = "" +
	"\n" +
	"!internal/pb/curso_categoria.proto\x12\x02pb\"\a\n" +
	"\x05Blank\"M\n" +
	"\tCategoria\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04nome\x18\x02 \x01(\tR\x04nome\x12\x1c\n" +
	"\tdescricao\x18\x03 \x01(\tR\tdescricao\"C\n" +
	"\x0fCreateCategoria\x12\x12\n" +
	"\x04nome\x18\x01 \x01(\tR\x04nome\x12\x1c\n" +
	"\tdescricao\x18\x02 \x01(\tR\tdescricao\"@\n" +
	"\x11ListaDeCategorias\x12+\n" +
	"\tcategoria\x18\x01 \x03(\v2\r.pb.CategoriaR\tcategoria2\x7f\n" +
	"\x10CategoriaService\x126\n" +
	"\x0eCriarCategoria\x12\x13.pb.CreateCategoria\x1a\r.pb.Categoria\"\x00\x123\n" +
	"\x0fListaCategorias\x12\t.pb.Blank\x1a\x15.pb.ListaDeCategoriasB\rZ\vinternal/pbb\x06proto3"

var (
	file_internal_pb_curso_categoria_proto_rawDescOnce sync.Once
	file_internal_pb_curso_categoria_proto_rawDescData []byte
)

func file_internal_pb_curso_categoria_proto_rawDescGZIP() []byte {
	file_internal_pb_curso_categoria_proto_rawDescOnce.Do(func() {
		file_internal_pb_curso_categoria_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_pb_curso_categoria_proto_rawDesc), len(file_internal_pb_curso_categoria_proto_rawDesc)))
	})
	return file_internal_pb_curso_categoria_proto_rawDescData
}

var file_internal_pb_curso_categoria_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_internal_pb_curso_categoria_proto_goTypes = []any{
	(*Blank)(nil),             // 0: pb.Blank
	(*Categoria)(nil),         // 1: pb.Categoria
	(*CreateCategoria)(nil),   // 2: pb.CreateCategoria
	(*ListaDeCategorias)(nil), // 3: pb.ListaDeCategorias
}
var file_internal_pb_curso_categoria_proto_depIdxs = []int32{
	1, // 0: pb.ListaDeCategorias.categoria:type_name -> pb.Categoria
	2, // 1: pb.CategoriaService.CriarCategoria:input_type -> pb.CreateCategoria
	0, // 2: pb.CategoriaService.ListaCategorias:input_type -> pb.Blank
	1, // 3: pb.CategoriaService.CriarCategoria:output_type -> pb.Categoria
	3, // 4: pb.CategoriaService.ListaCategorias:output_type -> pb.ListaDeCategorias
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_pb_curso_categoria_proto_init() }
func file_internal_pb_curso_categoria_proto_init() {
	if File_internal_pb_curso_categoria_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_pb_curso_categoria_proto_rawDesc), len(file_internal_pb_curso_categoria_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_pb_curso_categoria_proto_goTypes,
		DependencyIndexes: file_internal_pb_curso_categoria_proto_depIdxs,
		MessageInfos:      file_internal_pb_curso_categoria_proto_msgTypes,
	}.Build()
	File_internal_pb_curso_categoria_proto = out.File
	file_internal_pb_curso_categoria_proto_goTypes = nil
	file_internal_pb_curso_categoria_proto_depIdxs = nil
}
